/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Check/CheckPage': RouteRecordInfo<'/Check/CheckPage', '/Check/CheckPage', Record<never, never>, Record<never, never>>,
    '/Check/components/TheRecord': RouteRecordInfo<'/Check/components/TheRecord', '/Check/components/TheRecord', Record<never, never>, Record<never, never>>,
    '/Check/components/TheSet': RouteRecordInfo<'/Check/components/TheSet', '/Check/components/TheSet', Record<never, never>, Record<never, never>>,
    '/Check/SelectPage': RouteRecordInfo<'/Check/SelectPage', '/Check/SelectPage', Record<never, never>, Record<never, never>>,
    '/Defend/components/TheCamera': RouteRecordInfo<'/Defend/components/TheCamera', '/Defend/components/TheCamera', Record<never, never>, Record<never, never>>,
    '/Defend/components/TheFw': RouteRecordInfo<'/Defend/components/TheFw', '/Defend/components/TheFw', Record<never, never>, Record<never, never>>,
    '/Defend/components/TheInkjet': RouteRecordInfo<'/Defend/components/TheInkjet', '/Defend/components/TheInkjet', Record<never, never>, Record<never, never>>,
    '/Defend/components/TheLaser': RouteRecordInfo<'/Defend/components/TheLaser', '/Defend/components/TheLaser', Record<never, never>, Record<never, never>>,
    '/Defend/components/TheReader': RouteRecordInfo<'/Defend/components/TheReader', '/Defend/components/TheReader', Record<never, never>, Record<never, never>>,
    '/Defend/components/TheTest': RouteRecordInfo<'/Defend/components/TheTest', '/Defend/components/TheTest', Record<never, never>, Record<never, never>>,
    '/Defend/DefendPage': RouteRecordInfo<'/Defend/DefendPage', '/Defend/DefendPage', Record<never, never>, Record<never, never>>,
    '/Home/components/TheTable': RouteRecordInfo<'/Home/components/TheTable', '/Home/components/TheTable', Record<never, never>, Record<never, never>>,
    '/Home/HomePage': RouteRecordInfo<'/Home/HomePage', '/Home/HomePage', Record<never, never>, Record<never, never>>,
    '/Home/StationPage': RouteRecordInfo<'/Home/StationPage', '/Home/StationPage', Record<never, never>, Record<never, never>>,
    '/Search/components/TheDetail': RouteRecordInfo<'/Search/components/TheDetail', '/Search/components/TheDetail', Record<never, never>, Record<never, never>>,
    '/Search/components/TheDoc': RouteRecordInfo<'/Search/components/TheDoc', '/Search/components/TheDoc', Record<never, never>, Record<never, never>>,
    '/Search/components/TheRecord': RouteRecordInfo<'/Search/components/TheRecord', '/Search/components/TheRecord', Record<never, never>, Record<never, never>>,
    '/Search/components/TheTask': RouteRecordInfo<'/Search/components/TheTask', '/Search/components/TheTask', Record<never, never>, Record<never, never>>,
    '/Search/SearchPage': RouteRecordInfo<'/Search/SearchPage', '/Search/SearchPage', Record<never, never>, Record<never, never>>,
    '/Set/components/ThePass': RouteRecordInfo<'/Set/components/ThePass', '/Set/components/ThePass', Record<never, never>, Record<never, never>>,
    '/Set/SetPage': RouteRecordInfo<'/Set/SetPage', '/Set/SetPage', Record<never, never>, Record<never, never>>,
  }
}
