/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/bigScreen/batch/addBatch/': RouteRecordInfo<'/bigScreen/batch/addBatch/', '/bigScreen/batch/addBatch', Record<never, never>, Record<never, never>>,
    '/bigScreen/batch/addBatch/modal/successModal': RouteRecordInfo<'/bigScreen/batch/addBatch/modal/successModal', '/bigScreen/batch/addBatch/modal/successModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/batch/addBatch/modal/updateModal': RouteRecordInfo<'/bigScreen/batch/addBatch/modal/updateModal', '/bigScreen/batch/addBatch/modal/updateModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/batch/list/': RouteRecordInfo<'/bigScreen/batch/list/', '/bigScreen/batch/list', Record<never, never>, Record<never, never>>,
    '/bigScreen/batch/list/batchInfo': RouteRecordInfo<'/bigScreen/batch/list/batchInfo', '/bigScreen/batch/list/batchInfo', Record<never, never>, Record<never, never>>,
    '/bigScreen/batch/list/team-form': RouteRecordInfo<'/bigScreen/batch/list/team-form', '/bigScreen/batch/list/team-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/doc/': RouteRecordInfo<'/bigScreen/doc/', '/bigScreen/doc', Record<never, never>, Record<never, never>>,
    '/bigScreen/doc/doc-form': RouteRecordInfo<'/bigScreen/doc/doc-form', '/bigScreen/doc/doc-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/doc/docInfo': RouteRecordInfo<'/bigScreen/doc/docInfo', '/bigScreen/doc/docInfo', Record<never, never>, Record<never, never>>,
    '/bigScreen/error/': RouteRecordInfo<'/bigScreen/error/', '/bigScreen/error', Record<never, never>, Record<never, never>>,
    'MainTain': RouteRecordInfo<'MainTain', '/bigScreen/mainTain', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/consumables/': RouteRecordInfo<'/bigScreen/mainTain/consumables/', '/bigScreen/mainTain/consumables', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/moduleTest/': RouteRecordInfo<'/bigScreen/mainTain/moduleTest/', '/bigScreen/mainTain/moduleTest', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/moduleTest/Camera': RouteRecordInfo<'/bigScreen/mainTain/moduleTest/Camera', '/bigScreen/mainTain/moduleTest/Camera', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/moduleTest/InkjetPrinter': RouteRecordInfo<'/bigScreen/mainTain/moduleTest/InkjetPrinter', '/bigScreen/mainTain/moduleTest/InkjetPrinter', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/moduleTest/Laser': RouteRecordInfo<'/bigScreen/mainTain/moduleTest/Laser', '/bigScreen/mainTain/moduleTest/Laser', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/moduleTest/Reader': RouteRecordInfo<'/bigScreen/mainTain/moduleTest/Reader', '/bigScreen/mainTain/moduleTest/Reader', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/onlyTest/': RouteRecordInfo<'/bigScreen/mainTain/onlyTest/', '/bigScreen/mainTain/onlyTest', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/print/': RouteRecordInfo<'/bigScreen/mainTain/print/', '/bigScreen/mainTain/print', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/version/': RouteRecordInfo<'/bigScreen/mainTain/version/', '/bigScreen/mainTain/version', Record<never, never>, Record<never, never>>,
    '/bigScreen/mainTain/version/checkPwModal': RouteRecordInfo<'/bigScreen/mainTain/version/checkPwModal', '/bigScreen/mainTain/version/checkPwModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/addMore': RouteRecordInfo<'/bigScreen/module/addMore', '/bigScreen/module/addMore', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/finishedProduct': RouteRecordInfo<'/bigScreen/module/finishedProduct', '/bigScreen/module/finishedProduct', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/printPage': RouteRecordInfo<'/bigScreen/module/printPage', '/bigScreen/module/printPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/module/startPage': RouteRecordInfo<'/bigScreen/module/startPage', '/bigScreen/module/startPage', Record<never, never>, Record<never, never>>,
    '/bigScreen/newIndex': RouteRecordInfo<'/bigScreen/newIndex', '/bigScreen/newIndex', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/': RouteRecordInfo<'/bigScreen/search/', '/bigScreen/search', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/doc/': RouteRecordInfo<'/bigScreen/search/doc/', '/bigScreen/search/doc', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/doc/detailModal': RouteRecordInfo<'/bigScreen/search/doc/detailModal', '/bigScreen/search/doc/detailModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/doc/doc-form': RouteRecordInfo<'/bigScreen/search/doc/doc-form', '/bigScreen/search/doc/doc-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/record/': RouteRecordInfo<'/bigScreen/search/record/', '/bigScreen/search/record', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/record/detailModal': RouteRecordInfo<'/bigScreen/search/record/detailModal', '/bigScreen/search/record/detailModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/record/doc-form': RouteRecordInfo<'/bigScreen/search/record/doc-form', '/bigScreen/search/record/doc-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/task/': RouteRecordInfo<'/bigScreen/search/task/', '/bigScreen/search/task', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/task/task-form': RouteRecordInfo<'/bigScreen/search/task/task-form', '/bigScreen/search/task/task-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/team/': RouteRecordInfo<'/bigScreen/search/team/', '/bigScreen/search/team', Record<never, never>, Record<never, never>>,
    '/bigScreen/search/team/team-form': RouteRecordInfo<'/bigScreen/search/team/team-form', '/bigScreen/search/team/team-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/': RouteRecordInfo<'/bigScreen/searchCard/', '/bigScreen/searchCard', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/physicalDoc/': RouteRecordInfo<'/bigScreen/searchCard/physicalDoc/', '/bigScreen/searchCard/physicalDoc', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/physicalDoc/card': RouteRecordInfo<'/bigScreen/searchCard/physicalDoc/card', '/bigScreen/searchCard/physicalDoc/card', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/physicalDoc/detailModal': RouteRecordInfo<'/bigScreen/searchCard/physicalDoc/detailModal', '/bigScreen/searchCard/physicalDoc/detailModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/physicalDoc/doc-form': RouteRecordInfo<'/bigScreen/searchCard/physicalDoc/doc-form', '/bigScreen/searchCard/physicalDoc/doc-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/record/': RouteRecordInfo<'/bigScreen/searchCard/record/', '/bigScreen/searchCard/record', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/record/card': RouteRecordInfo<'/bigScreen/searchCard/record/card', '/bigScreen/searchCard/record/card', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/record/detailModal': RouteRecordInfo<'/bigScreen/searchCard/record/detailModal', '/bigScreen/searchCard/record/detailModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/record/doc-form': RouteRecordInfo<'/bigScreen/searchCard/record/doc-form', '/bigScreen/searchCard/record/doc-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/task/': RouteRecordInfo<'/bigScreen/searchCard/task/', '/bigScreen/searchCard/task', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/task/card': RouteRecordInfo<'/bigScreen/searchCard/task/card', '/bigScreen/searchCard/task/card', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/task/task-form': RouteRecordInfo<'/bigScreen/searchCard/task/task-form', '/bigScreen/searchCard/task/task-form', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/team/': RouteRecordInfo<'/bigScreen/searchCard/team/', '/bigScreen/searchCard/team', Record<never, never>, Record<never, never>>,
    '/bigScreen/searchCard/team/team-form': RouteRecordInfo<'/bigScreen/searchCard/team/team-form', '/bigScreen/searchCard/team/team-form', Record<never, never>, Record<never, never>>,
    'Setting': RouteRecordInfo<'Setting', '/bigScreen/setting', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/Oldset': RouteRecordInfo<'/bigScreen/setting/Oldset', '/bigScreen/setting/Oldset', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/set': RouteRecordInfo<'/bigScreen/setting/set', '/bigScreen/setting/set', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/sort/': RouteRecordInfo<'/bigScreen/setting/sort/', '/bigScreen/setting/sort', Record<never, never>, Record<never, never>>,
    '/bigScreen/setting/sort/setPwModal': RouteRecordInfo<'/bigScreen/setting/sort/setPwModal', '/bigScreen/setting/sort/setPwModal', Record<never, never>, Record<never, never>>,
    '/bigScreen/test': RouteRecordInfo<'/bigScreen/test', '/bigScreen/test', Record<never, never>, Record<never, never>>,
    '/bigScreen/workstationStatus/': RouteRecordInfo<'/bigScreen/workstationStatus/', '/bigScreen/workstationStatus', Record<never, never>, Record<never, never>>,
    '/bigScreen/workstationStatus/card': RouteRecordInfo<'/bigScreen/workstationStatus/card', '/bigScreen/workstationStatus/card', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
